name: Tests

on: [push]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      # simple_animations  
      - name: simple_animations / Remove example
        run: rm -rf example/
        working-directory: .

      - name: simple_animations / Get dependencies
        run: flutter pub get
        working-directory: .

      - name: simple_animations / Run tests
        run: flutter test
        working-directory: .
        
